name: 'Huawei Cloud Software Repository for Container (SWR) Login'
description: 'Log in to a container registry'
inputs:
  access-key-id:
    description: 'Access key id'
    required: true
  access-key-secret:
    description: 'Secret access key'
    required: true
  region:
    description: 'Region'
    required: true
branding:
  icon: 'cloud'
  color: 'red'
runs:
  using: 'node12'
  main: 'dist/index.js'
